apiVersion: batch/v1
kind: CronJob
metadata:
  name: time-printer-app
  labels:
    app: time-printer
    app.kubernetes.io/instance: time-printer
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    metadata:
      labels:
        app: time-printer
        app.kubernetes.io/instance: time-printer
    spec:
      template:
        metadata:
          labels:
            app: time-printer
            app.kubernetes.io/instance: time-printer
        spec:
          restartPolicy: OnFailure
          containers:
            - name: app
              image: python:3.11-slim
              imagePullPolicy: IfNotPresent
              command:
                - python
                - /scripts/print_time.py
              volumeMounts:
                - name: script
                  mountPath: /scripts
          volumes:
            - name: script
              configMap:
                name: time-printer-script
