apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
  - cronjob.yaml

namePrefix: time-printer-

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app: time-printer
      app.kubernetes.io/instance: time-printer

patches:
  - target:
      kind: CronJob
    patch: |-
      - op: replace
        path: /spec/schedule
        value: "*/5 * * * *"

configMapGenerator:
  - name: script
    files:
      - script.py=print_time.py
