apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: Root
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: 'apps'
    server: 'https://kubernetes.default.svc'
  source:
    path: apps
    repoURL: 'https://github.com/lansfy/argocdtest.git'
    targetRevision: HEAD
    directory:
      recurse: false
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
