apiVersion: batch/v1
kind: CronJob
metadata:
  name: app
  labels:
    app: app
    app.kubernetes.io/instance: app
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    metadata:
      labels:
        app: app
        app.kubernetes.io/instance: app
    spec:
      template:
        metadata:
          labels:
            app: app
            app.kubernetes.io/instance: app
        spec:
          restartPolicy: OnFailure
          containers:
            - name: app
              image: python:3.11-slim
              imagePullPolicy: IfNotPresent
              command:
                - python
                - /scripts/script.py
              volumeMounts:
                - name: script
                  mountPath: /scripts
          volumes:
            - name: script
              configMap:
                name: script
